### ISSUE TITLE
resumption of activity

### ISSUE THREAD

**Issue by Koles1910** [grimaldello/the-crims-italian-bot-v2#35] opened 2023-05-22 19:15 UTC
you could make it so that after the attack and won the fight (saved the fight in a file or somewhere on the page) or escape after e.g. 30 seconds, resume hunting because now if I win the fight it stops the script and I have to start it again

**Comment by Koles1910** [comment] 2023-05-23 14:49
you might have done?

**Comment by grimaldello** [comment] 2023-05-23 17:24
Hi @Koles1910,
thank you for your reporting.

What you are asking is already implemented (if I understand your request correctly).
Is there any error in browser console when happen what you said?

It would be great if you provide a video or similar so I can better investigate.

**Comment by Koles1910** [comment] 2023-05-23 17:32
there is no error just stops and the red dot stays in place after attacking and leaving the club and nothing else happens

**Comment by grimaldello** [comment] 2023-05-23 19:25
Could you please paste here the values of these properties:
![image](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/9029075/f0820406-6804-4d0b-9fbb-e414a03fd9dc)

From my side it's not so simple to test since I need to grow up my account :)
I see if I can grow up and make some tests.

**Comment by Koles1910** [comment] 2023-05-23 19:55
[https://up.be3.ovh/upload/1684871624.png](url)
please, I will test how to catch someone, but after the attack, nothing happens, I have to start the script again

**Comment by grimaldello** [comment] 2023-05-23 20:47
What is that `koniec` in the first row of your 2nd screenshot?

The last 2 error rows they are not blocker errors and are caused by the crims (you can find that last two errors even hunting manually theoretically).

I made attack on random guy (much stronger than me) and the bot attacked correctly.
If the problem is after a won fight, then I think it's very hard for me to test it.

**Comment by Koles1910** [comment] 2023-05-23 21:05
after each attack, whether won or not, I will aim, but I will try, the bot stops, and you have to start again, and my point is to keep hunting after the attack

**Comment by Koles1910** [comment] 2023-05-23 21:08
after each attack, whether won or not, I will aim, but I will try, the bot stops, and you have to start again, and my point is to keep hunting after the attack
finish = Assault took: ${(finish - start) / 1000} seconds`

**Comment by grimaldello** [comment] 2023-05-23 21:13
> after each attack, whether won or not, I will aim, but I will try, the bot stops, and you have to start again, and my point is to keep hunting after the attack finish = Assault took: ${(finish - start) / 1000} seconds`

Is it a line of code you add by yourself?
If yes please remove it (and any other row you add) and try again.

That syntax you paste here seems wrong to me (or paste here a screenshot with that code part so I can better analyze it)

**Comment by grimaldello** [comment] 2023-05-23 21:16
In original `release.js` file that part is the following one:
![image](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/9029075/81f10922-ea01-4f97-aced-d5b636efdb6e)

If you modify it by yourself you must be sure it's a correct Javascript syntax

**Comment by Koles1910** [comment] 2023-05-23 21:19
I downloaded the release file again and it works, I must have configured something wrong somewhere, and now it works and continues to attack after the attack, sorry for the headache, and is there a save to the file or the attacks somewhere?

**Comment by grimaldello** [comment] 2023-05-23 21:27
No problem :)

You mean save the console logs?
If yes, right mouse click on a log and click on Save all Messages to File:
![image](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/9029075/050e7ae2-1d35-4899-97ae-34b5ec859921)

The you can open with a text editor and search or remove what you need.
If file is very big I suggest you to use editor that not reads the whole file once opened (such as [Gloog](https://klogg.filimonov.dev/))

**Comment by Koles1910** [comment] 2023-05-23 21:34
I mean the recording of the assault so that I can write down who and how many statistics I gained

**Comment by grimaldello** [comment] 2023-05-23 21:42
There is no direct method to save the assaults you made.

A method you can use to to track the assaults you made is to save all the messages to a file (as I wrote in the previous post) and then open the file with a text editor and find/filter all the strings of assault.

As alternative you can see the directly in The Crims, by going in: Profile > Logs > Single Assaults

**Comment by Koles1910** [comment] 2023-05-24 05:57
ok thanks, I don't want to open a new topic for now, I have one more question to which file I have to add this code below (removes the img) so that in theory the page loads faster :)
`document.addEventListener('DOMContentLoaded', function() {
  var elements = Array.from(document.querySelectorAll('div')).filter(function(element) {
    var backgroundImage = getComputedStyle(element).getPropertyValue('background-image');
    return backgroundImage.includes('/static/images/menu/menu-sprites.png');
  });
  elements.forEach(function(element) {
    element.style.display = 'none';
  });

  var image = document.querySelector('img[src="https://static-live.thecrims.com/static/images/tc-menu-logo.png"]');
  if (image) {
    image.style.display = 'none';
  }

  var avatar = document.querySelector('img[src="https://static-live.thecrims.com/static/images/avatars/avatar_1.jpg"]');
  if (avatar) {
    avatar.style.display = 'none';
  }
});
`

**Comment by grimaldello** [comment] 2023-05-24 06:38
Probably the best way is disable the image loading from browser settings.

Take a look here:
https://support.mozilla.org/en-US/questions/1226175#:~:text='More%20Information'.-,Under%20the%20Permissions%20tab%2C%20scroll%20down%20to%20'Load%20images
','%20and%20check%20'Block'.&text=Thank%20you%20for%20your%20response.

**Comment by Koles1910** [comment] 2023-05-24 06:48
your suggestion looks like this
https://up.be3.ovh/upload/1684910865.png
and after my modifications yes
https://up.be3.ovh/upload/1684910900.png
so i want to upload it to the file

**Comment by grimaldello** [comment] 2023-05-24 07:29
You mean that you want to block only some specific images?

However, I'm busy at the moment, cannot take a look where to put that code.

By the way, can you measure the real speed boost with the blocked image? Is
it something meaningful or is it very low?

**Comment by Koles1910** [comment] 2023-05-24 07:32
if you have a moment, check where to put it, in my eye you can see an increase in speed

**Comment by grimaldello** [comment] 2023-05-24 17:24
You can put the following lines, before all the codes of the bot:
```
document.querySelector('img[src*="https://static-live.thecrims.com/static/images/avatars/"]').style.display = "none";
document.querySelector('img[src*="https://static-live.thecrims.com/static/images/tc-menu-logo.png"]').style.display= 'none';

HERE BELOW ALL THE BOT CODES

```
![image](https://github.com/grimaldello/the-crims-italian-bot-v2/assets/9029075/f41a147a-8e9b-42de-a27f-2f24478a7135)

Better to use the contains (*=) than the equals "operator" (for the logo not really useful, but for the avatar it is more flexible

**Comment by Koles1910** [comment] 2023-05-24 17:35
ok but is it in the bot file and generate or generated?

**Comment by grimaldello** [comment] 2023-05-24 18:33
In the example above it is in the already generated `release.js` file.

But it can be added also in the source code and enabled/disabled with a property.
If you want this, please open a new issue with the request (and I close this one that has become tangled)

**Closed** 2023-05-24 18:45 UTC
